GenSpectrum/dashboard-components

components/src/temporal.ts
Resolves #1 
The solution comes from https://github.com/iamkun/dayjs/issues/1242
=> fix: import dayjs plugins from esm not directly

components/index.html, components/src/components/dateRangeSelector/date-range-selector.stories.ts, components/src/components/dateRangeSelector/date-range-selector.ts
Resolves #81, resolves #80
This adds a event and a submit button to the date range selector. The event contains the dateFrom and dateTo of the selector.
=> feat(components): add gs-date-range-changed event to date range selector

components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/dateRangeSelector/dateConversion.ts, components/src/web-components/input/date-range-selector-component.stories.ts, components/tests/dateRangeSelector.spec.ts
The play function of storybook does not support pressing enter on the input form. This required to do for testing. Thus, we moved the test to playwright, where this is possible.
=> fix(components): move flaky date range test to playwright

components/src/preact/mutationComparison/mutation-comparison-venn.tsx
Reusing the label that the ChartJS plugin generates for tooltips: `Some variant ∩ Other variant`
=> Venn label

components/src/preact/textInput/__mockData__/aggregated_hosts.json, components/src/preact/textInput/fetchAutocompleteList.ts, components/src/preact/textInput/test-input.stories.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/location-filter-component.stories.ts, components/src/web-components/input/text-input-component.stories.ts, components/src/web-components/input/text-input-component.tsx
resolves #113
Adds a text input field. It fires an event, when the input matches possible values (gathered from LAPIS through aggregated with fields).
=> Text input

components/.eslintignore, components/package.json, components/src/web-components/app.ts, examples/React/.gitignore, examples/React/README.md, examples/React/index.html, examples/React/package.json, examples/React/src/App.tsx, examples/React/src/main.tsx, examples/React/src/vite-env.d.ts, examples/React/tsconfig.json, examples/React/tsconfig.node.json, examples/React/vite.config.ts, examples/plainJavascript/README.md, examples/plainJavascript/index.html
=> feat(examples): add example React app to demonstrate how to use the components 

components/package.json, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/textInput/text-input.stories.tsx, components/src/web-components/input/date-range-selector-component.stories.ts, components/src/web-components/input/date-range-selector-component.tsx, components/src/web-components/input/location-filter-component.stories.ts, components/src/web-components/input/location-filter-component.tsx, components/src/web-components/input/text-input-component.stories.ts, components/src/web-components/input/text-input-component.tsx, examples/React/src/App.tsx
related to #129
Provide JSDoc annotations and `HTMLElementEventMap` entries for the events that our input elements fire.
(and fix Storybook such that the "Actions" tab shows the events again)
With the help of the `HTMLElementEventMap`, typescript can infer the type of the event in the React app:
=> docs(components): annotate components that fire events

components/src/operator/FetchInsertionsOperator.ts, components/src/operator/FetchSubstitutionsOrDeletionsOperator.ts, components/src/preact/mutationComparison/__mockData__/nucleotideMutationsOtherVariant.json, components/src/preact/mutationComparison/__mockData__/nucleotideMutationsSomeVariant.json, components/src/preact/mutations/__mockData__/nucleotideMutations.json, components/src/utils/mutations.spec.ts, components/src/utils/mutations.ts
resolves #123
Removes the mutation cache and uses the parsed mutations directly from LAPIS.
Also fixes wrongly assigned position to mock data.
=> refactor(components): remove mutation cache

.commitlintrc.js, .github/dependabot.yml, .github/workflows/commitlint.yml, package-lock.json, package.json
resolves #147
Using https://commitlint.js.org/.
I enforced that a scope is present in the message. If we notice that it feels too restrictive, we can remove that check later.
The last dependabot commit broke the `body-max-line-length` default of 100, so I set it to 200.
=> build(root): lint commit messages

components/src/preact/components/chart.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bubble-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-line-chart.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage-chart.tsx, components/src/preact/shared/charts/LogitScale.ts
resolves #144
The logit scale is added to the ScaleTypeRegistry of chart.js. So the type is now correctly asserted.
=> fix(components): fix types of logit scale #144

.github/pull_request_template.md, .github/workflows/storybook.yml, .github/workflows/tests.yml, components/.storybook-preact/main.ts, components/.storybook/preview.ts, components/README.md, components/package.json, components/src/web-components/PreactLitAdapter.tsx, components/src/web-components/input/location-filter-component.stories.ts, components/src/web-components/input/location-filter-component.tsx, components/src/web-components/input/location-filter.mdx, components/src/web-components/input/text-input-component.stories.ts
resolves #129
This is mostly meant to update the README as a preparation to publish a first version as an NPM package.
This also sketches how we can document components using Storybook. If you like this approach, we can create follow-up issues to document all existing components.
This is the Storybook docs page for the location filter. Most parts of this are autogenerated from the `custom-elements.json`.
=> Start to document components

components/.prettierignore, components/.prettierrc.js, components/.prettierrc.json
=> chore(components): make prettier ignore the CHANGELOG.md since it's autogenerated

.github/workflows/release-components.yml
Apparently, `release_created` is only set when creating a release for the root of the repo. Instead, it seems that we can use `components--release_created`.
https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#path-outputs
=> build(components): fix workflow steps after release created

components/package.json
This seems to be the equivalent of `npm publish --access public`
https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package#publishing-a-public-organization-scoped-package
=> fix(components): configure public access for scoped packages

.github/workflows/release-components.yml
"Please note that you need to set the registry-url to https://registry.npmjs.org/ in setup-node to properly configure your credentials." https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
=> build(components): setup node to create .npmrc when releasing

components/README.md
so that it also points to the correct location on the NPM package page
=> docs(components): use absolute link for examples

components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/web-components/input/mutation-filter-component.stories.ts
resolves #157
Shows an info element on the mutation filter and adds examples on the placeholder text.
=> fix(components): show an info element on mutation filter #157

components/src/preact/components/csv-download-button.tsx, components/src/preact/mutationComparison/getMutationComparisonTableData.spec.ts, components/src/preact/mutationComparison/getMutationComparisonTableData.ts, components/src/preact/mutationComparison/mutation-comparison-table.tsx, components/src/preact/mutations/getInsertionsTableData.spec.ts, components/src/preact/mutations/getInsertionsTableData.ts, components/src/preact/mutations/getMutationsTableData.spec.ts, components/src/preact/mutations/getMutationsTableData.ts, components/src/preact/mutations/mutations-insertions-table.tsx, components/src/preact/mutations/mutations-table.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/shared/sort/sortInsertions.spec.ts, components/src/preact/shared/sort/sortInsertions.ts, components/src/preact/shared/sort/sortSubstitutionsAndDeletions.spec.ts, components/src/preact/shared/sort/sortSubstitutionsAndDeletions.ts
resolves #153
Refactors the table for the mutations and mutation comparison, so that is uses the mutation type directly instead of its string representation.
=> refactor(components): use mutations directly in table instead of string representation 

components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/components/info.stories.tsx, components/src/preact/components/info.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx
resolves #193
The info component can now be passed children to show. The size of the tooltip increases by the size of the displayed children. The size can also be provided as a prop.
=> feat: info button opens a scrollable info panel

components/src/web-components/input/mutation-filter-component.stories.ts, components/src/web-components/input/mutation-filter-component.tsx
=> docs(components): documents mutation filter component #201

.github/workflows/release-components.yml
Apparently https://github.com/google-github-actions/release-please-action is deprecated, they move it to https://github.com/googleapis/release-please-action.
=> chore(github-actions): google-github-actions/release-please-action is deprecated, migrate to new namespace

.commitlintrc.js, components/.storybook/ComponentDocsBlock.ts, components/src/web-components/app.stories.ts, components/src/web-components/display/aggregate-component.stories.ts, components/src/web-components/display/aggregate-component.tsx, components/src/web-components/display/mutation-comparison-component.stories.ts, components/src/web-components/display/mutation-comparison-component.tsx, components/src/web-components/display/mutations-component.stories.ts, components/src/web-components/display/mutations-component.tsx, components/src/web-components/display/prevalence-over-time-component.stories.ts, components/src/web-components/display/relative-growth-advantage-component.stories.ts, components/src/web-components/input/date-range-selector-component.stories.ts, components/src/web-components/input/location-filter-component.stories.ts, components/src/web-components/input/mutation-filter-component.stories.ts, components/src/web-components/input/text-input-component.stories.ts
resolves #210
BREAKING CHANGE: rename components: `gs-aggregate-component` to `gs-aggregate`, `gs-mutation-comparison-component` to `gs-mutation-comparison`, `gs-mutations-component` to `gs-mutations`
=> unify component tags

components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/components/error-boundary.stories.tsx, components/src/preact/components/error-boundary.tsx, components/src/preact/components/error-display.stories.tsx, components/src/preact/components/error-display.tsx, components/src/preact/components/loading-display.stories.tsx, components/src/preact/components/loading-display.tsx, components/src/preact/components/no-data-display.tsx, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/app.stories.ts, components/src/web-components/app.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-input.stories.ts, components/src/web-components/input/gs-text-input.tsx, components/tests/snapshots.spec.ts
resolves #143
Adds a error boundary to each component. This will catch every error thrown in its children. If the error is a `UserFacingError` then the content of the error message will also be shown. Otherwise it will be omitted. The error should take up as much space as the original component. 
This also introduces a loading skeleton for those components, which have this state.
When the reference genome can not be fetched, an error banner will be shown.
Error banner when error while fetching reference genome.
=> feat(components): add error boundary to components

components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx, components/tests/dateRangeSelector.spec.ts
resolves #213
BREAKING CHANGE: Add mandatory dateColumn prop to date range selector 
As last time: I wasn't able to use the play function to click on the selectors. Therefore no tests were added.
=> feat(components): configurable target column for date range selector

components/src/web-components/app.ts, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-text-input.tsx, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
resolves #236
Neither Storybook nor the custom elements manifest seem to provide support for marking required properties there.
The prevalence over time docs:
=> docs(components): mark required attributes

components/src/lapisApi/lapisApi.ts, components/src/lapisApi/lapisTypes.ts, components/src/preact/components/error-display.stories.tsx, components/src/preact/components/error-display.tsx, components/src/preact/locationFilter/fetchAutocompletionList.ts, components/src/web-components/input/gs-location-filter.stories.ts
resolves #75
Show the error message from LAPIS when the call to fetch the autocomplete list fails. The error details are shown in a separate modal.
=> fix(components): `gs-location-filter`: show better error

components/src/operator/RenameFieldOperator.spec.ts, components/src/operator/RenameFieldOperator.ts, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/query/queryPrevalenceOverTime.ts, components/src/query/queryRelativeGrowthAdvantage.ts, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.stories.ts, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
resolves #215
`gs-relative-growth-advantage` now has an attribute `lapisDateField`.
=> feat(components): make x-axis date field of `gs-relative-growth-advantage` configurable

components/src/preact/locationFilter/location-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx
resolves  #265
If the value is not present, explicitly set it to undefined. That way, receivers can overwrite previously set values by using the spread operator on the event details.
Event details may look like:
```typescript
{
country: undefined,
division: undefined,
location: undefined,
region: "Asia",
}
```
=> feat(components): gs-location-filter: set all values in `gs-location-changed` event details

components/package-lock.json, components/package.json, components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/components/info.stories.tsx, components/src/preact/components/info.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.tsx, examples/React/src/App.tsx
resolves #235
The info component, now resizes to a smaller size, when on a small screen. This way it should not go outside of the screen. It still is next to the info button. (When the maintainer of a website decides to put the info button outside of the viewport also the info text will be displayed outside. This can also be the case for the prevalence over time component on mobile view. This issue will be adressed in #234)
Also the mutation filter component is redisigned, so it works better with the info button and is more similar to loculus input field.
=> 235 make info button mobile friendly

components/src/preact/dateRangeSelector/date-range-selector.tsx
resolves #269
The date range selector now changes it size depending on the available size. It first shows all three elements (dropdown, date from, date to) on one row, then the dropdown on the first and the two dates on the second, and lastly all on a separate line.
=> feat(components): responsive date range selector

components/package-lock.json, components/package.json, components/src/preact/components/SegmentSelector.tsx, components/src/preact/components/checkbox-selector.tsx, components/src/preact/components/dropdown.tsx, components/src/preact/components/info.tsx, components/src/preact/components/mutation-type-selector.tsx, components/src/preact/components/proportion-selector-dropdown.tsx, components/src/preact/components/tabs.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/preact/shared/floating-ui/hooks.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx
resolves #234
The toolbar now wraps when there is not enough space. First the whole toolbar wraps, then each element. 
Some dropdown components now use floating-ui, so the position to the correct side when wrapping
~~- [] The implemented feature is covered by an appropriate test.~~
=> feat(components): mobile friendly tabs

components/src/preact/locationFilter/location-filter.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-text-input.stories.ts
resolves #263
location filter and text input now fire an event, when the input field is empty. The content is then the field with an "undefined" value.
=> 263 gs location filter if value becomes empty then also fire event

components/src/preact/dateRangeSelector/date-range-selector.tsx
resolves #283
This removes the default height from the date range selector, so it works as expected on small screens. The error boundary still uses the default height, so when the component throws an error, then the component will shrink to this size.
=> fix(components): remove date range selector fixed height for responsive design

components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx
resolves #273
Adds a placeholder text to the location-filter, similar to text-input.
=> feat(components): placeholderText for location-filter

components/src/preact/aggregatedData/aggregate-table.tsx, components/src/preact/aggregatedData/aggregate.stories.tsx, components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/components/table.stories.tsx, components/src/preact/components/table.tsx, components/src/preact/mutationComparison/mutation-comparison-table.tsx, components/src/preact/mutationComparison/mutation-comparison.stories.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutations/mutations-grid.tsx, components/src/preact/mutations/mutations-insertions-table.tsx, components/src/preact/mutations/mutations-table.tsx, components/src/preact/mutations/mutations.stories.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-table.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/web-components/visualization/gs-aggregate.stories.ts, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.stories.ts, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations.stories.ts, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx
resolves #271
Lets the maintainer set the paginationLimit for all tables. It can either be a number, which sets the number of rows, or a boolean. A value of  `true` produces the default pagination from gridjs. A value of `false` will disable pagination.
This targets the first step of #271. The other will be done in a separate PR.
=> feat(components): allow to set pagination limit for all tables

components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bubble-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-line-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage-chart.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/preact/shared/charts/getYAxisMax.ts, components/src/preact/shared/charts/getYAxisScale.ts, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.stories.ts, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
resolves #264
Lets the maintainer select the maximum on the y axis for linear and logarithmic view. The logit scale is untouched. This will be addressed by another PR.
The max value can either be a number, or set to `maxInData`, which uses the maximum of the data in the chart as a max value for the y-axis, or set to `limitTo1`, which uses the lower value of the maximum of the data or 1.
=> feat(components): make y-axis max value configurable

components/src/preact/aggregatedData/aggregate-table.tsx, components/src/query/queryAggregateData.ts
resolves #270
This fixes the issue, that the sorting with null values did not work. It seems to be a bug in gridjs.
Ascending
Descending
=> fix(components): correct sorting with null values in gs-aggregate

components/src/preact/dateRangeSelector/date-range-selector.tsx
resolves #284
This reduces the smallest size of the datepicker for the two row design. The limit is now 240px. Below that it will be the stacked design. This change was made possible by reducing the size prop of the input component. The size of the Select component was adjusted, so it matches the min-width of the input fields with size 7.
This is now the element, with a width of 240px. 
=> feat(components): reduce the smallest size of the date picker in two row design

components/src/preact/numberSequencesOverTime/number-sequences-over-time.stories.tsx, components/src/preact/numberSequencesOverTime/number-sequences-over-time.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx, components/src/query/queryAggregatedDataOverTime.ts, components/src/query/queryNumberOfSequencesOverTime.spec.ts, components/src/query/queryNumberOfSequencesOverTime.ts, components/src/query/queryPrevalenceOverTime.ts, components/src/utils/sort.ts, components/src/utils/utils.ts, components/src/web-components/visualization/gs-number-sequences-over-time.tsx, components/src/web-components/visualization/index.ts, components/vitest.setup.ts
resolves #327
This does the basic setup of the new component and fetches the data. Properly displaying the data will follow in the next PRs.
=> Number sequences over time: implement skeleton

components/src/query/queryMutationsOverTime.spec.ts, components/src/query/queryMutationsOverTime.ts, components/src/web-components/visualization/gs-mutations-over-time.stories.ts
Sets the min proportion to 0.001 of the initial mutations queries, so we don't overload the browser with data. This is now the same as in covSpectrum.
=> feat(components): set min proportion for initial query to 0.001

components/src/preact/components/tooltip.stories.tsx, components/src/preact/components/tooltip.tsx, components/src/preact/mutationsOverTime/getFilteredMutationsOverTime.spec.ts, components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/query/queryMutationsOverTime.spec.ts, components/src/query/queryMutationsOverTime.ts, components/src/utils/temporal.spec.ts, components/src/utils/temporal.ts
resolves #353 
Adds a tooltip for each cell of the mutation over time component. Also fixes the wrong calculation of the last day of the iso week.
- ~~[] All necessary documentation has been adapted.~~
=> 353 mutations over time add tooltip

components/src/preact/components/tooltip.stories.tsx, components/src/preact/components/tooltip.tsx, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
We switched from using floatingUi to position the tooltip to css only. This uses now less computing power. However, this current also means that the tooltip takes up space at the bottom and at the left of the grid (See screenshot). 
This is a draft to show a possible solution
Tooltip in center of grid
Tooltip at bottom left of grid
=> Position tooltip for mutation over time using css not floatingUi

components/src/preact/components/info.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/web-components/visualization/gs-prevalence-over-time.tsx
This adds, for the prevalence-over-time component, the exact code of the component to the info box and adds a link to CodePen to try it out.
Info box:
CodePen:
=> feat(components): add code example and link to codepen to info box

components/src/preact/numberSequencesOverTime/number-sequences-over-time.tsx, components/src/preact/useQuery.ts
resolves #395
Fixes the issue that the storybook does not update the component when changing the granularity or smoothing window. There were missing dependencies in the useQuery function.
=> fix(components): rerender number of sequences over time when input changes 

components/src/preact/components/checkbox-selector.stories.tsx, components/src/preact/components/checkbox-selector.tsx
resolves #361
This adds two buttons to the checkbox dropdown so users can select all or none of the checkboxes.
For the screenshot I hovered over the 'Select none' button.
=> segment selector make it possible to deselect all values at once

components/src/preact/components/percent-input.stories.tsx, components/src/preact/components/percent-intput.tsx, components/src/preact/components/proportion-selector-dropdown.stories.tsx, components/src/preact/components/proportion-selector.stories.tsx, components/src/preact/components/proportion-selector.tsx, components/src/preact/mutations/mutations-grid.tsx
resolves #421 
This introduces a fix for the proportion selector, so users can input values with a comma/dot. Also this adds a delay to the proportion filter. It will now update the `setMinProportion` and `setMaxProportion` after that delay with the latest value. This way only one filter action will be performed by the `mutations-over-time` component and the `mutations` component.
- ~~[ ] The implemented feature is covered by an appropriate test.~~ But the storybook test will now wait for the new value to be set.
=> 421 mutations over time add delay for proportion filter

components/src/operator/FetchAggregatedOperator.ts, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_01.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_02.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_03.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_04.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_05.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_06.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_2024_07.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_20_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_21_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_22_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_23_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_24_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_25_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_26_01_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_tooManyMutations_total.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_week3_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_week4_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_week5_2024.json, components/src/preact/mutationsOverTime/__mockData__/aggregated_week6_2024.json, components/src/preact/mutationsOverTime/getFilteredMutationsOverTime.spec.ts, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/preact/mutationsOverTime/mutations-over-time.stories.tsx, components/src/query/queryMutationsOverTime.spec.ts, components/src/query/queryMutationsOverTime.ts, components/src/web-components/visualization/gs-mutations-over-time.stories.ts
closes #386
* query aggregated without `fields` for every date range to get the total count
* display the total count in the tooltip
I wasn't sure how to display the tooltip exactly. I put it in the same line with the count, because an extra line uses even more space for the tooltip, which makes positioning harder.
=> feat(components): mutations over time: also show total number of available sequences in tooltip

components/src/web-components/app.ts, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-input.tsx, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations-over-time.tsx, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-number-sequences-over-time.tsx, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.tsx, examples/React/src/App.tsx
I tried to add some react support for our components. I'm not sure, if this is the right way. At least the idea no longer complains. The documentation of the components also does not show, which it does in astro.
=> feat(components): add react support

components/.gitignore, components/package-lock.json, components/package.json, components/src/index.ts, components/src/preact/dateRangeSelector/computeInitialValues.spec.ts, components/src/preact/dateRangeSelector/computeInitialValues.ts, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/dateRangeSelector/dateRangeOption.ts, components/src/preact/dateRangeSelector/selectableOptions.ts, components/src/preact/mutationsOverTime/MutationOverTimeData.ts, components/src/preact/mutationsOverTime/getFilteredMutationsOverTime.spec.ts, components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/query/queryMutationsOverTime.ts, components/src/utils/map2d.spec.ts, components/src/utils/map2d.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx, components/tests/dateRangeSelector.spec.ts, examples/React/src/App.tsx, examples/plainJavascript/index.html
resolves #473
The date range selector doesn't come with predefined date ranges anymore. Users of the component need to supply themselves.
We provide the old options as constants for convenient use.
=> feat(components): gs-date-range-selector: replace `customSelectOptions` by `dateRangeOptions`

components/src/operator/SlidingOperator.ts, components/src/preact/prevalenceOverTime/__mockData__/numeratorFilterNoData.json, components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bubble-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-line-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
Resolves #502
Adds a guard against missing data. It then shows "No data available". Also fixes the error, that when no data is returned the sliding window still works.
Moreover, a general guard was introduced to each of the charts (bar, line, bubble), so they don't throw an error, when they get no data.
=> fix(components): show no data message for prevalence over time

components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.tsx
resolves #
In https://github.com/GenSpectrum/dashboard-components/pull/500#discussion_r1843558199 we discovered that blur dispatch events are not working as intended. (e.g. it did not fire if a user moved outside of the component if they moved outside after deleting mutations). We decided that this functionality is not needed and is tedious to implement so we will just remove it. 
The dispatch event was unused by dashboards (we use the change events dispatch event instead).
=> feat(components): remove handleOnBlur function and dispatch event from MutationFilterInner

components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/preact/webWorkers/useWebWorker.ts
Resolves #509
Fixes the bug, that the mutation over time component in storybook does not update on controls change
=> fix(components): mutation over time worker runs on message change

components/src/preact/mutationsOverTime/__mockData__/noDataWhenNoMutationsAreInFilter.ts, components/src/preact/mutationsOverTime/__mockData__/noDataWhenThereAreNoDatesInFilter.ts, components/src/preact/mutationsOverTime/mutationOverTimeWorker.mock.ts, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/preact/mutationsOverTime/mutations-over-time.stories.tsx, components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/query/queryMutationsOverTime.spec.ts, components/src/query/queryMutationsOverTime.ts
Resolves: #501
Resolves: #487
Shows a "No data available" indication, when there is no data for the lapis filters. Also adds a no data message, for the filters the user can select in the component itself.
When the user selects a too narrow filter in the component
=> fix(components): show no data indicator on mutation over time instead of error

components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/mutationFilter/parseAndValidateMutation.ts, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.tsx
resolves https://github.com/GenSpectrum/dashboard-components/issues/481, https://github.com/GenSpectrum/dashboard-components/issues/482
1. Instead of having to press the `+` button after typing in a mutation we parse the user's input and check if it is a valid mutation. If the input is valid we show that option in a dropdown. It can be selected from the dropdown (via a click or hitting the enter button), adding it to the list of selected mutation filters. This is more intuitive for users. 
Covspectrum uses the same approach. 
The code is similar to `asyncSelect` from [react-select](https://react-select.com/home), but has been implemented in preact and is specific for the mutation filter case.
2. Allow users to paste a ',' or ';' separated list of mutations into the search bar - accept all …
=> feat(components): Use a dropdown for selecting valid mutations and allow a comma separated list as input for mutation filter

components/src/preact/webWorkers/useWebWorker.ts, components/src/preact/webWorkers/workerFunction.ts
Apparently, the concrete error type doesn't make it across the wire. Any error type that you send back from a web worker will be deserialized as a plain `Error`.
=> fix(components): propagate UserFacingErrors through the web worker

components/README.md, components/package.json, components/src/componentsEntrypoint.ts, components/src/standaloneEntrypoint.ts, components/src/utilEntrypoint.ts, components/vite.release-standalone.config.ts, components/vite.release.config.ts, examples/React/src/App.tsx, examples/plainJavascript/index.html
BREAKING CHANGE: DateRangeOption and dateRangeOptionPresets now in own sub package
When importing our components utility functions (like dateRangeOptionPresets) in a node environment or on the server side of an astro application we get an error, that "HTMLElement not defined". This message occurs, because the lit element class extends HTMLElement. 
To provide users of our package also access to our utility functions, we put them into an own sub-package. They can now be imported through e.g.: `import { dateRangeOptionPresets } from '@genspectrum/dashboard-components/util';`
=> feat(components): export utils as extra entrypoint

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
resolves #538
This is a draft, since we need to decide at which width should the numbers be hidden. Currently, I tried to use roughly the width of the entry '100%' .
Hides the numbers on the proportion cells in the mutation over time component, when the cell is too small to show the number. 
This is a fix. Right now it hides the numbers dependent on the width of the full table. This does not work, since there can be a variable number of columns.
This is the smallest width, where the numbers are still showing:
=> fix(components): hide proportion on width of cell

components/src/preact/components/no-data-display.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/query/queryRelativeGrowthAdvantage.ts
resolves #506
* show a nice error when we can't connect to the cov spectrum server
* when the cov spectrum server errors, we assume that it didn't have enough data to compute a fit
=> feat(components): gs-relative-growth-advantage: show better errors when fit fails

components/src/preact/textInput/text-input.stories.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/gs-text-input.tsx
Resolves: #571
Validates the input of gs-text-input and changes the default value of "initialValue" and "placeholderText" to undefined.
=> fix(components): gs-text-input: validate attributes

components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/preact/shared/charts/getYAxisMax.ts, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
=> fix(components): gs-relative-growth-advantage: validate attributes

components/src/web-components/app.stories.ts, components/src/web-components/app.ts
=> fix(components): gs-app: validate attributes

components/src/web-components/visualization/gs-sequences-by-location.stories.ts, components/src/web-components/visualization/gs-sequences-by-location.tsx
https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes 
According to the HTML spec a boolean attribute can only bet set to `true` by setting it. Absence it considered as false which only works if also the default is false.
=> fix(components): set default of `enableMapNavigation` to false

components/src/preact/components/error-display.tsx, components/src/preact/components/info.tsx, components/src/preact/components/modal.stories.tsx, components/src/preact/components/modal.tsx, components/src/preact/map/sequences-by-location-map.tsx
=> refactor(components): extract modal component

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
Resolves: #634
resolves #
This change was necessary, so the tooltip does not reach out of the containing tab window, if there are only few entries. 
This is a quick fix of the bug. It does not work a component with a small height (below 250px). There the tooltip height of the tooltip is larger than the box. Thus the user can not hover on the elment and read the tooltip at the same time. But since this is no usefull component height, it is left out of the considerations.
=> fix(components): show mutation over time tooltip below value on first six rows

components/src/preact/map/sequences-by-location-map.tsx, examples/plainJavascript/index.html
because it broke the plain JS example - for some reason the browser complained that Leaflet doesn't export a "default" export.
=> fix(components): don't use Leaflet default export

components/src/preact/components/downshift-combobox.tsx, components/src/preact/lineageFilter/LineageFilterChangedEvent.ts, components/src/preact/lineageFilter/lineage-filter.stories.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/preact/locationFilter/LocationChangedEvent.ts, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/textInput/TextInputChangedEvent.ts, components/src/preact/textInput/text-input.tsx, components/src/types.ts, components/src/utilEntrypoint.ts, components/src/web-components/input/gs-lineage-filter.stories.ts, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-text-input.tsx
resolves #654
Downshift is now used for the lineage filter.
Breaking change: renames initialValue to value to be in line with the generic input element.
The input with delete button
=> 654 gs lineage filter add button to delete current input

components/src/preact/components/downshift-combobox.tsx, components/src/preact/lineageFilter/fetchLineageAutocompleteList.spec.ts, components/src/preact/lineageFilter/fetchLineageAutocompleteList.ts, components/src/preact/lineageFilter/lineage-filter.stories.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/preact/locationFilter/fetchAutocompletionList.spec.ts, components/src/preact/locationFilter/fetchAutocompletionList.ts, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/textInput/fetchAutocompleteList.ts, components/src/preact/textInput/fetchStringAutocompleteList.ts, components/src/preact/textInput/text-input.stories.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/gs-lineage-filter.stories.ts, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-text-input.stories.ts, components/src/web-components/input/gs-text-input.tsx
resolves #609
Adds the option to provide a lapis filter to the text-input, location-filter and lineage-filter. The filter is applied to limit the select options.
=> 609 filter autocomplete options of location filter text input and location filter

components/src/preact/components/downshift-combobox.tsx, components/src/preact/textInput/fetchStringAutocompleteList.spec.ts, components/src/preact/textInput/fetchStringAutocompleteList.ts, components/src/preact/textInput/text-input.tsx
Resolves #664
Shows counts on the dropdown of the gs-text-input. 
=> feat(components): gs-text-input: show count on autocomplete options

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
resolves #
confirmed this also works with a dashboards change
=> Alternative_grid_size

components/src/query/queryWastewaterMutationsOverTime.spec.ts, components/src/query/queryWastewaterMutationsOverTime.ts
Otherwise, there would just be a type error complaining about `null` somewhere.
resolves #
=> fix(components): gs-wastewater-mutations-over-time: throw proper error when there is an invalid mutation

components/src/preact/components/downshift-combobox.tsx, components/src/preact/locationFilter/fetchAutocompletionList.spec.ts, components/src/preact/locationFilter/fetchAutocompletionList.ts, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts
=> feat(components): gs-location-filter: show counts in autocomplete options

components/src/preact/components/mutation-info.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutations/mutations.tsx
resolves #465
I reused parts of the `gs-mutations` info text.
=> feat(components): gs-mutation-comparison: add info text

components/src/preact/mutationFilter/ExampleMutation.tsx, components/src/preact/mutationFilter/mutation-filter-info.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/web-components/input/gs-mutation-filter.stories.ts
Fixes the error on the gs-mutation-filter component, when a reference genome is provided with no genes.
Its mostly a refactoring.
=> fix(components): gs-mutation-filter: allow for reference genome with no genes

components/.storybook-preact/preview.ts, components/src/preact/dateRangeSelector/computeInitialValues.spec.ts, components/src/preact/dateRangeSelector/computeInitialValues.ts, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/dateRangeSelector/dateRangeOption.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx, examples/React/src/App.tsx, examples/plainJavascript/index.html
resolves #683
Now you can supply a `value` to this component. It serves as an initial value, if the attribute doesn't change. If the attribute changes, then the component will switch to use that value.
BREAKING CHANGE: gs-date-range-selector: remove `initialValue`, `initialDateFrom`, `initialDateTo`. Use `value` instead.
=> feat(components): gs-date-range-selector: make the component controllable from a surrounding JS app

components/src/preact/components/error-boundary.tsx
* Take the "Text input - Default" story
* change the `lapisField` to "hos" (i.e. making it an invalid field)
* The component will show an error, because LAPIS shows an error
* change  the `lapisField` to "host" (i.e. making it a valid field again)
Before: It would still show an error until you click "Try again" 
Now: It rerenders and doesn't show an error anymore
Related to https://github.com/GenSpectrum/dashboards/issues/530
=> fix(components): reset error when the component props have changed

components/.eslintrc.json, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx
Due to using `@property({ type: Object })`, lit would always `JSON.parse` the attribute:
- `value="Last month"` would be invalid, because it's not a valid JSON string
- using additional quotes like `value=""Last month""` would be valid, because that is a valid JSON string
- `value="2021"` would be invalid, because JSON.parse would parse it into a number, which is not accepted by the zod schema
This make sure that we treat everything as a string if it doesn't parse into an object.
JSON strings (with the additional quotes) will still be treated as a string.
We didn't notice this in Storybook, because due to using
```
html`<gs-date-range-selector .value=${args.value}/>`
```
it seems that lit directly set the properties in the class instead of passing it via text in the HTML
(i.e. setting the …
=> fix(components): gs-date-range-selector `value`: make sure that strings are recognized as strings

components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-bubble-chart.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time-line-chart.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage-chart.tsx
While reviewing #713 I noticed that some of the chart configs aren't memoized. I believe we can boost the performance a little by wrapping them in a `useMemo`.
=> refactor(components): memoize some chart configs

components/src/preact/sequencesByLocation/sequences-by-location-table.tsx, components/src/preact/sequencesByLocation/sequences-by-location.stories.tsx, components/src/preact/sequencesByLocation/sequences-by-location.tsx
The table view of `gs-sequences-by-location` crashes when LAPIS doesn't return any data for the specified filters.
Before:
After:
=> fix(components): gs-sequences-by-location: don't crash table view when there is no data

components/src/preact/ReferenceGenomeContext.ts, components/src/preact/components/ReferenceGenomesAwaiter.tsx, components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx
=> feat(components): gs-mutation-filter: show error when the reference genomes are empty

components/src/preact/ReferenceGenomeContext.ts, components/src/web-components/PreactLitAdapter.tsx, components/src/web-components/gs-app.ts
This is a follow-up to #743.
In the dashboards, the gs-mutation-filter would on the first render get the default of `gs-app`, which will throw and display an error:
"UserFacingError: This organism has neither nucleotide nor amino acid sequences configured in its reference genome. You cannot filter by mutations." To prevent that, we should use the same "uninitialized value" as for the Preact context.
=> fix(components): initialize the reference genomes context with a value that is recognized as "uninitialized"

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
=> fix(components): gs-mutations-over-time: hide x-axis labels when there is no data to be displayed

components/src/preact/components/downshift-combobox.tsx
On the dashboards, usually the location filter would update it's combobox items as follows:
* fetch the autocomplete options
* render the autocomplete options
* change the lapisFilter (e.g. by changing the selected date range)
* fetch the autocomplete options
* show the loading state, unmounting the combobox and __forgetting the old autocomplete options__
* render the new autocomplete options
https://github.com/GenSpectrum/dashboards/pull/539 had red e2e tests, because the following happened:
* fetch autocomplete options for a filter that would return no option
* change the lapisFilter before the first fetch finishes to something that would return a number of options
* the first fetch finishes and persists zero autocomplete items in a `useState`
* the second fetch finishes, but its items …
=> fix(components): make sure to render the downshift combobox with the correct items

components/src/preact/components/annotated-mutation.tsx
resolves #778
Apparently Firefox doesn't let you copy the content of a button.
=> fix(components): make it possible to copy an annotated mutation in Firefox

components/src/preact/components/clearable-select.stories.tsx, components/src/preact/components/clearable-select.tsx, components/src/preact/components/downshift-combobox.tsx, components/src/preact/dateRangeFilter/computeInitialValues.spec.ts, components/src/preact/dateRangeFilter/computeInitialValues.ts, components/src/preact/dateRangeFilter/date-picker.tsx, components/src/preact/dateRangeFilter/date-range-filter.stories.tsx, components/src/preact/dateRangeFilter/date-range-filter.tsx, components/src/preact/dateRangeFilter/dateRangeOption.ts, components/src/preact/shared/WithClassName/WithClassName.ts, components/src/preact/shared/icons/DeleteIcon.tsx, components/src/preact/shared/stories/expectOptionSelected.tsx, components/src/utilEntrypoint.ts, components/src/web-components/input/gs-date-range-filter.stories.ts, components/src/web-components/input/gs-date-range-filter.tsx, components/tailwind.config.mjs
resolves #719
- Allows to provide "undefined" as a value to the date range filter component. 
- Allows to remove value from input
- Adapt design, so it has rounded borders, like the other filter components
With value:
With undefined value
With only one date defined
=> 719 date range selector add undefined status

components/src/preact/dateRangeFilter/computeInitialValues.spec.ts, components/src/preact/dateRangeFilter/computeInitialValues.ts, components/src/preact/dateRangeFilter/date-range-filter.stories.tsx, components/src/preact/dateRangeFilter/date-range-filter.tsx, components/src/preact/dateRangeFilter/dateRangeOption.ts, components/src/web-components/input/gs-date-range-filter.stories.ts, components/src/web-components/input/gs-date-range-filter.tsx
Discovered in the context of https://github.com/GenSpectrum/dashboards/issues/617
The code seems to have sent `undefined` with the event "gs-date-range-option-changed", but both Chrome and Firefox show `null` as event.detail.
=> fix(components): gs-date-range-filter make it explicit that the event contains `null` when deleting the input

components/src/preact/sequencesByLocation/leafletStyleModifications.css
Chrome has a default CSS enty that enables "bounding boxes" around SVG paths when selecting them; Firefox does not show those (by default). Explicitly disable them as they are distracting.
resolves #729
=> fix(components): disable outline selecting map regions in Chrome

components/package-lock.json, components/package.json
In the last dependency update (#818), `vite-plugin-dts` was upgraded from 4.5.0 to 4.5.3. After that, our JSX.IntrinsicElements declarations (e.g. this one: https://github.com/GenSpectrum/dashboard-components/blob/0c7d6cab120e59295db70495b4467b4c1e463dae/components/src/web-components/gs-app.ts#L110-L117) were not included in the built output anymore (in `dist/components.d.ts`). Thus, the typecheck in the dashboards failed, claiming that e.g. `gs-app` is not a valid JSX component name. 4.5.0 is the last version that works.
https://github.com/qmhc/vite-plugin-dts/issues/419 seems to be the exact same issue.
=> fix(components): pin `vite-plugin-dts` to 4.5.0 to export JSX.IntrinsicElements namespace declarations

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
Resolves: #809
resolves #
The issue was, that the text of the accessiblitiy entry "No data" was wrapped and therefore needed more space.
=> fix(components): prevent mutation cell layout shift

components/README.md, examples/plainJavascript/package.json, examples/plainJavascript/vite.config.js
Fixes the following error for the plain js example:
The issue was the wrong export from leaflet, which is then used as commonjs and not esm.
=> fix(examples): fix commonjs import of leaflet for plain js

components/src/preact/dateRangeFilter/date-picker.tsx, components/src/web-components/input/gs-date-range-filter.tsx
Resolves #806
Flatpickr has a built in method to render the calendar to other elements. I just used that. This way the calendar is inside the shadow dom and we can move the css of flatpickr inside our components.
We can see if we can use this also for our other dropdown components.
=> feat(components): render calendar inside shadow dom

CONTRIBUTING.md, components/.storybook-preact/applyDaisyUiToRootInsteadOfHost.css, components/.storybook-preact/preview.ts, components/.storybook/preview.tsx, components/README.md, components/package.json, components/src/preact/components/info.tsx, components/src/preact/components/min-max-range-slider.tsx, components/src/preact/components/table.tsx, components/src/preact/dateRangeFilter/date-picker.tsx, components/src/styles/replaceCssProperties.stories.tsx, components/src/styles/replaceCssProperties.ts, components/src/styles/tailwind.css, components/src/web-components/PreactLitAdapter.tsx, components/src/web-components/PreactLitAdapterWithGridJsStyles.tsx, components/src/web-components/gs-app.stories.ts, components/src/web-components/gs-app.ts, components/vite.release-standalone.config.ts, components/vite.release.config.ts, examples/React/src/App.tsx, examples/plainJavascript/index.html
resolves #807
resolves #804
See https://daisyui.com/docs/config/#root
The default is
```
@plugin "daisyui" {
root: ':root';
}
```
which only targets the HTML document. We need to apply the styles to `:host`.
=> fix(components): apply daisyui styles to host instead of root

components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts
This fixes a bug that causes `<gs-mutations-over-time ... displayMutations='["ORF1a:T103L"]' />` to ignore the specified mutation and show nothing because the gene contains a lowercase `a`.
=> fix(components): bug with displayMutations in mutations-over-time

components/src/preact/components/downshift-combobox.tsx, components/src/preact/textFilter/text-filter.stories.tsx
resolves #812
We have to control the `selectedItem` ourselves instead of leaving it to downshift, because otherwise it will be reset to the `value` that is provided to the web component.
=> feat(components): gs-text-input: make it possible to paste values and accept them on blur

components/src/preact/components/downshift-combobox.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/textFilter/text-filter.stories.tsx, components/src/preact/textFilter/text-filter.tsx, components/src/web-components/input/gs-text-filter.stories.ts
resolves #848
Because downshift assumes that an `undefined` `value` means it's uncontrolled. For the "nothing is selected" state we should make sure to use `null` instead.
~~- [] All necessary documentation has been adapted.~~
=> refactor(components): make sure that the Downshift value is never `undefined`

components/src/utilEntrypoint.ts
Exports the input type of the new NumberRangeFilter so they can be used at the consuming side.
=> feat(components): export input type of NumberRangeFilter

components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts, components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.stories.tsx, components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
Resolves #866
Adds the same mutation filter, that we already have for gs-mutations-over-time, now to the gs-wastewater-mutations-over-time. The filter value is applied to all tabs.
=> feat(components): add mutation filter to gs-wastewater-mutations-over-time

components/src/lapisApi/LineageDefinition.ts, components/src/preact/lineageFilter/fetchLineageAutocompleteList.spec.ts
resolves #920
This PR make the components to accept lineage definition files from LAPIS where `aliases` are not defined.
- ~[ ] All necessary documentation has been adapted.~
=> fix(components): accept lineage definitions without "aliases" key

components/README.md
related to #949
Document that you need to reinstall the test-runner for MacOS to make it work.
- ~~The implemented feature is covered by an appropriate test.~~
=> docs(components): document test runner install info for MacOS
