GenSpectrum/dashboard-components

.github/workflows/tests.yml, components/package.json, components/src/components/container/component-container.ts, components/src/components/container/component-toolbar-button-checkboxes.ts, components/src/components/mutations-grid.ts, components/src/components/mutations-table.ts, components/src/components/mutations.ts, components/src/components/prevalence-over-time-bubble-chart.ts, components/src/components/prevalence-over-time-line-bar-chart.ts, components/src/components/prevalence-over-time-table.ts, components/src/components/prevalence-over-time.ts, components/src/components/relative-growth-advantage-chart.ts, components/src/components/relative-growth-advantage.ts, components/src/components/tooltip.ts, components/src/operator/DivisionOperator.ts, components/src/operator/FetchAggregatedOperator.ts, components/src/operator/FetchMutationsOperator.ts, components/src/operator/GroupByAndSumOperator.ts, components/src/operator/GroupByOperator.ts, components/src/query/queryPrevalenceOverTime.ts, components/src/temporal.ts, components/src/types.ts, components/src/utils.spec.ts, components/src/utils.ts
=> ci: add workflow for linting, formatting and testing

components/src/components/prevalence-over-time-bubble-chart.ts, components/src/components/prevalence-over-time-line-bar-chart.ts, components/src/components/prevalence-over-time-table.ts, components/src/components/prevalence-over-time.ts, components/src/query/queryPrevalenceOverTime.ts
resolves #18
Screenshot:
Does anyone have a better idea for the headings of the table columns?
This could be an alternative approach:
=> feat: show count in "prevalence over time" table #18

components/src/tailwind-element.ts
Tailwind does not seem to be used fully without this fix
=> fix: make css fully available for tailwind and daisyui

components/.storybook/main.ts, components/package-lock.json, components/package.json, components/src/components/container/component-scaling-selector.stories.ts, components/src/storybook/withinShadowRoot.story.ts
resolves #42
https://storybook.js.org/docs/essentials/interactions
https://storybook.js.org/docs/writing-tests/interaction-testing
=> test(components): implement a basic test for a component using Storybook

.github/workflows/tests.yml, components/package-lock.json, components/package.json
resolves #43
There is now a new workflow `storybook_test.yml` which runs the storybook tests in the ci. 
- caching for playwright browsers is used
- the storybook needs no be deployed first, before the tests can run (intended behavior)
=> ci: run storybook tests in ci

components/index.html, components/src/components/locationFilter/location-filter.stories.ts, components/src/components/locationFilter/location-filter.ts
=> feat: implement custom event when location filter is submitted

components/src/storybook-declarations.d.ts
Resolves #24
Removes the workaround for the type declarations of actions.
=> chore(components): remove workaround for addon-actions

components/src/preact/prevalenceOverTime/prevalence-over-time-bubble-chart.tsx
=> feat(components): show tooltip count and total count on bubble plot to first digit

LICENSE, components/LICENSE, components/package.json
=> chore(root,components): add AGPL 3 license

components/src/web-components/input/index.ts
=> fix(components): export MutationFilterComponent

components/package.json
`npm publish` told me
```
npm ERR! code EPRIVATE
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```
=> fix(components): make package public

.github/workflows/release-components.yml
Make it a proper multiline command so that both commands are executed.
=> build(components): fix build step

.github/workflows/tests.yml, components/.depcheckrc.json, components/package-lock.json, components/package.json, components/src/preact/components/min-max-range-slider.tsx, components/src/preact/components/percent-intput.tsx
We already use this in CoV-Spectrum: https://github.com/GenSpectrum/cov-spectrum-website/blob/720762c8bc7fe9a290bb442da5eb81ca753e5885/.depcheckrc.json
It actually detected a React import (only a type, but still) that should not have been there.
=> build(components): use depcheck to check for unused/missing dependencies

components/package.json, components/tailwind.config.cjs
=> feat(components): disable dark mode in daisyui

components/src/web-components/app.mdx, components/src/web-components/app.stories.ts, components/src/web-components/app.ts
=> docs(components): document `gs-app`

.github/workflows/tests.yml, components/package-lock.json, components/package.json, components/src/preact/components/ReferenceGenomesAwaiter.tsx, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/textInput/text-input.stories.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/date-range-selector-component.stories.ts, components/src/web-components/input/date-range-selector-component.tsx, components/src/web-components/input/location-filter-component.stories.ts, components/src/web-components/input/location-filter-component.tsx, components/src/web-components/input/mutation-filter-component.stories.ts, components/src/web-components/input/mutation-filter-component.tsx, components/src/web-components/input/text-input-component.stories.ts, components/src/web-components/input/text-input-component.tsx, examples/React/src/App.tsx
resolves #190
BREAKING CHANGE: rename `value` to `initialValue` in `gs-location-filter`
=> feat!(components): all input components should have a `initialValue` attribute

components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/web-components/input/date-range-selector-component.stories.ts, components/src/web-components/input/date-range-selector-component.tsx
=> docs(components): document `gs-date-range-selector`

components/src/web-components/display/prevalence-over-time-component.stories.ts, components/src/web-components/display/prevalence-over-time-component.tsx
=> docs(components): document `gs-prevalence-over-time`

components/src/web-components/display/relative-growth-advantage-component.stories.ts, components/src/web-components/display/relative-growth-advantage-component.tsx
=> docs(components): document `gs-relative-growth-advantage`

components/src/preact/aggregatedData/aggregate.stories.tsx, components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/components/headline.stories.tsx, components/src/preact/components/headline.tsx, components/src/preact/mutationComparison/mutation-comparison.stories.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutations/mutations.stories.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/web-components/display/aggregate-component.stories.ts, components/src/web-components/display/aggregate-component.tsx, components/src/web-components/display/mutation-comparison-component.stories.ts, components/src/web-components/display/mutation-comparison-component.tsx, components/src/web-components/display/mutations-component.stories.ts, components/src/web-components/display/mutations-component.tsx, components/src/web-components/display/prevalence-over-time-component.stories.ts, components/src/web-components/display/prevalence-over-time-component.tsx, components/src/web-components/display/relative-growth-advantage-component.stories.ts, components/src/web-components/display/relative-growth-advantage-component.tsx
resolves #192
Lets users enter an own (optional) headline for the display components.
=> feat(components): optional configurable headline of components

components/src/web-components/input/date-range-selector-component.tsx, components/src/web-components/input/text-input-component.stories.ts, components/src/web-components/input/text-input-component.tsx
=> docs(components): documents text input component #202

components/src/web-components/visualization/mutations-component.tsx, components/src/web-components/visualization/prevalence-over-time-component.tsx
=> docs(components): fix default value, fix type

components/src/web-components/input/mutation-filter-component.tsx
=> docs(components): show concrete type in Storybook docs

components/src/web-components/ResizeContainer.mdx
resolves #221
Adds a short section for the size prop
=> docs(components): section for size prop

components/src/constants.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-input.stories.ts, components/src/web-components/input/gs-text-input.tsx, components/src/web-components/input/introduction.mdx, components/src/web-components/introduction.mdx, components/src/web-components/visualization/gs-aggregate.stories.ts, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.stories.ts, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations.stories.ts, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.stories.ts, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
resolves #164
and use the production open LAPIS instance.
=> docs(components): overall cleanup

components/src/web-components/input/gs-location-filter.stories.ts
=> docs(components): fix location filter code example

README.md, components/package-lock.json, components/package.json, components/src/preact/components/error-boundary.tsx, components/src/preact/components/error-display.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutationComparison/queryMutationData.ts, components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/query/queryPrevalenceOverTime.ts, components/src/types.ts, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx, examples/React/src/App.tsx, examples/plainJavascript/index.html, examples/plainJavascript/package.json, package-lock.json, package.json
resolves #209
Instead of passing 
```
{
displayName: 'EG',
country: 'USA',
pangoLineage: 'EG*',
dateFrom: '2023-01-01' 
}
``` 
to `gs-prevalence-over-time`, now you have to pass
```
{ 
displayName: 'EG',
lapisFilter: {
country: 'USA',
pangoLineage: 'EG*',
dateFrom: '2023-01-01' 
}
},
```
=> make namedlapisfilter a nested structure

components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx
=> feat(components): gs-location-filter: remove submit button

examples/React/src/App.tsx, examples/plainJavascript/index.html
- ~~[] All necessary documentation has been adapted.~~
=> chore(examples): use prod LAPIS for examples

.commitlintrc.js, components/src/preact/dateRangeSelector/computeInitialValues.spec.ts, components/src/preact/dateRangeSelector/computeInitialValues.ts, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/dateRangeSelector/selectableOptions.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx
=> `gs-date-range-selector`: set initial `dateFrom` and  `dateTo` values from `initialValue` 

README.md, components/CHANGELOG.md, components/README.md, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-input.tsx, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
Changes all files with old repo name to new repo name
=> refactor(root): rename repository to dashboard-components

.github/scripts/preview-changelog.sh, .github/workflows/changelog-preview.yml, package.json
resolves #299
Adds a sticky note to each PR with the changlog, or a message that there are no changes in the changelog
=> ci(components): show preview of changelog on pr

components/src/web-components/input/gs-mutation-filter.tsx
Otherwise, lit doesn't correctly deserialize values passed into the property.
=> fix(components): mutation filter: `initialValue` must be of `type Object`

components/src/lapisApi/ReferenceGenome.ts, components/src/preact/mutationFilter/mutation-filter-info.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/mutationFilter/sequenceTypeFromSegment.spec.ts, components/src/preact/mutationFilter/sequenceTypeFromSegment.ts, components/src/web-components/input/gs-mutation-filter.stories.ts
resolves #182
This was mainly taken from Loculus. I tweaked it a little to adapt it to the reference genomes.
Single-segmented:
Multi-segmented:
=> feat(components): mutation filter: add explanation to info box

components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx, components/src/preact/textInput/text-input.tsx
Just a little refactoring. Fewer lines of code, easier to maintain.
=> refactor(components): use spread operator to simplify passing on inner props

components/src/web-components/visualization/gs-number-sequences-over-time.tsx
=> docs(components): number sequences over time: complete component docs

components/src/preact/lineageFilter/__mockData__/aggregated.json, components/src/preact/lineageFilter/fetchLineageAutocompleteList.spec.ts, components/src/preact/lineageFilter/fetchLineageAutocompleteList.ts, components/src/preact/lineageFilter/lineage-filter.stories.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/web-components/input/gs-lineage-filter.stories.ts, components/src/web-components/input/gs-lineage-filter.tsx
resolves #324
This is mostly copied from the text input, but I kept it separate on purpose, because the implementations might change once we support more lineage systems in this component.
=> feat(components): add lineage filter component

components/src/web-components/input/index.ts
=> fix(components): export lineage filter

components/src/query/queryRelativeGrowthAdvantage.ts, components/src/utils/temporal.ts
If the input values are narrowed to a specific version of `Temporal`, the result will also be typed to that specific version.
=> refactor(components): improve types of `getMinMaxTemporal`

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/query/queryMutationsOverTime.ts, components/src/web-components/visualization/gs-mutations-over-time.tsx
resolves #367
Throwing a `UserFacingError` so that the user can see what went wrong.
Maybe we should adapt the error display a little so that it becomes easier to see what went wrong (instead of having to click on the "show details" button)
=> fix(components): mutations over time: limit the number of rows and columns that can be displayed in the grid

components/vite.release.config.ts
resolves #399
This PR changes the vite release config to create a bundle that includes all dependencies.
@fengelniederhammer, @JonasKellerer, do you see some disadvantages of doing that?
=> ci(components): provide a standalone JS bundle

components/README.md
(This is mostly to trigger a new NPM package release.)
=> feat(components): add NPM badge to README

.github/workflows/changelog-preview.yml
=> ci(github-actions): improve changelog preview messages to clarify what they mean

components/src/preact/aggregatedData/aggregate.tsx, components/src/preact/mutations/mutations.tsx, components/src/preact/numberSequencesOverTime/number-sequences-over-time.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/tests/snapshots.spec.ts
...namely: Aggregate, Mutations, NumberSequencesOverTime, and PrevalenceOverTime
I'll document mutations over time and mutation comparison in a later PR.
=> feat(components): add info texts for four components

components/src/preact/components/loading-display.tsx
closes #292
This is what the React example page looks like with throttling using the browser tools:
[Bildschirmaufzeichnung vom 01.08.2024, 17:47:03.webm](https://github.com/user-attachments/assets/8fdedc67-734f-4df5-8d54-7c2b4c75abc0)
=> fix(components): reduce flashiness of loading skeletons

components/src/preact/components/percent-intput.tsx, components/src/preact/components/proportion-selector.tsx
closes #115
* IMO a tiny UI feature - no test required
=> feat(components): proportion selector: indicate error when min percentage > max percentage

components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-input.tsx, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations-over-time.tsx, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-number-sequences-over-time.tsx, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.tsx
=> docs(components): consistently test that types of web components and Preact components match

components/src/web-components/input/gs-text-input.tsx
Fix error, that gs-text-input got wrong label for react support.
=> fix(components): fix react type of gs-text-input

CONTRIBUTING.md, README.md, components/README.md
resolves #463
* Providing an as-short-as-possible overview
* moving commitlint and release please details to CONTRIBUTING.md
* referencing the components README for more details
=> docs(root): restructure root README for better guidance

components/src/web-components/introduction.mdx
I noticed that the introduction page of our Storybook docs is a bit sparse for someone who doesn't know the components.
=> docs(components): mention how to install and use the components in the Storybook introduction

components/.eslintrc.json, components/src/preact/components/error-display.tsx
resolves #
https://eslint.org/docs/latest/rules/curly
=> ci(components): enforce curly braces around if statement code blocks

components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.stories.tsx
Fixes the relative growth advantage story for preact. It did not use the mock and therefore showed a different result (an error) than the web components story.
=> fix(components): fix preact story of relative growth advantage

components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/web-components/visualization/gs-mutations-over-time.tsx
resolves #441
Add text to the info box.
=> feat(components): add info text for mutations-over-time component

components/package.json
Dependabot doesn't know how to link our components:
Maybe this will help.
=> chore(components): add `repository` to package.json

components/src/preact/components/chart.tsx
I found this while looking through the code and thought it might be good to clean it up.
=> fix(components): remove corresponding event listeners when destroying a graph

components/src/preact/mutationFilter/parseMutation.spec.ts, components/src/preact/mutationFilter/sequenceTypeFromSegment.ts, components/src/utils/mutations.ts
=> fix(components): gs-mutation-filter: make input fully case-insensitive

components/src/preact/mutationComparison/mutation-comparison-venn.tsx
=> refactor(components): simply render the description - we don't need `useEffect`

components/src/preact/components/error-boundary.tsx, components/src/preact/components/error-display.tsx, components/src/preact/dateRangeSelector/computeInitialValues.spec.ts, components/src/preact/dateRangeSelector/computeInitialValues.ts, components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/dateRangeSelector/dateRangeOption.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-date-range-selector.tsx
resolves #557
This is a proof of concept how we can use zod to validate component attributes.
=> fix(components): gs-date-range-selector: validate component attributes

components/src/preact/dateRangeSelector/date-range-selector.tsx, components/src/preact/lineageFilter/lineage-filter.tsx, components/src/web-components/input/gs-date-range-selector.tsx, components/src/web-components/input/gs-lineage-filter.tsx
=> fix(components): gs-lineage-filter: validate attributes 

components/src/web-components/visualization/gs-aggregate.tsx
=> fix(components): fix gs-aggregate name in `HTMLElementTagNameMap` and `IntrinsicElements`

components/src/preact/components/error-display.tsx, components/src/preact/mutationComparison/mutation-comparison.tsx, components/src/types.ts, components/src/utilEntrypoint.ts
=> fix(components): gs-mutation-comparison: validate attributes

components/src/preact/dateRangeSelector/date-range-selector.stories.tsx, components/src/preact/lineageFilter/lineage-filter.stories.tsx, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/shared/stories/expectInvalidAttributesErrorMessage.ts, components/src/web-components/input/gs-location-filter.tsx
Resolves: #568
Adds validation to the location filter component. Also allows for undefined as placeholder and initialValue. 
Also adds tests to checks for default values of the location, lineage and date range filter.
=> fix(components): gs-location-filter: validate attributes

components/src/preact/mutationFilter/mutation-filter.tsx, components/src/utilEntrypoint.ts, components/src/web-components/input/gs-mutation-filter.stories.ts
Resolves: #570
Validates the input of gs-mutation-filter
=> fix(components): gs-mutation-filter: validate attributes

components/src/preact/mutations/mutations.tsx, components/src/types.ts, components/src/web-components/visualization/gs-mutations.tsx
Resolves: #573 
Added the validation of the input and slighly adjust the filter description.
=> fix(components): gs-mutations: validate attributes

components/src/preact/mutationsOverTime/mutations-over-time.stories.tsx, components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/types.ts, components/src/utilEntrypoint.ts, components/src/web-components/visualization/gs-mutations-over-time.tsx
=> fix(components): gs-mutations-over-time: validate attributes

components/src/preact/numberSequencesOverTime/number-sequences-over-time.stories.tsx, components/src/preact/numberSequencesOverTime/number-sequences-over-time.tsx, components/src/types.ts, components/src/web-components/visualization/gs-number-sequences-over-time.tsx
=> fix(components): gs-number-sequences-over-time: validate attributes

components/src/preact/components/tabs.tsx
=> fix(components): don't crash components when someone passes empty `views` attribute

components/src/preact/statistic/statistics.tsx
=> fix(components): gs-statistics: validate attributes

components/src/preact/prevalenceOverTime/prevalence-over-time.stories.tsx, components/src/preact/prevalenceOverTime/prevalence-over-time.tsx, components/src/preact/shared/charts/confideceInterval.ts, components/src/preact/shared/charts/getYAxisMax.ts, components/src/types.ts, components/src/utilEntrypoint.ts, components/src/web-components/visualization/gs-prevalence-over-time.tsx
=> fix(components): gs-prevalence-over-time: validate attributes

components/src/preact/components/error-display.tsx
=> Better zod error details

components/src/preact/components/error-boundary.stories.tsx, components/src/preact/components/error-boundary.tsx
=> fix(components): update error boundary to validate all props

components/src/utilEntrypoint.ts
=> feat(components): export type `MapSource`

components/src/preact/aggregatedData/aggregate.tsx
=> fix(components): gs-aggregate: rerender when `initialSortField` or `initialSortDirection` changes

components/src/preact/mutationFilter/mutation-filter-info.tsx
resolves #637
Single segmented case:
Multi segmented case:
=> feat(components): gs-mutation-filter: add quickstart guide to info text

components/package-lock.json, components/package.json, components/src/preact/downshift_types.d.ts, components/src/preact/locationFilter/LocationChangedEvent.ts, components/src/preact/locationFilter/fetchAutocompletionList.spec.ts, components/src/preact/locationFilter/fetchAutocompletionList.ts, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/utilEntrypoint.ts, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx, examples/React/src/App.tsx, examples/plainJavascript/index.html
BREAKING CHANGE: gs-location-filter prop initialValue changed to value, a json with the event value
BREAKING CHANGE: gs-location-changed event now returns null for unspecified value
Resolves: #267
This is the second try of #622.
This now uses the downshift library to present a selectable dropdown menu. It allows for easy search, keyboard useage, delete button and has a focus on accessibility.
I chose to use the same style as before to show the hirarchy of the elements. I did not use the "... country in" section, so that the user does not have to specify the labels for the single entries. I could not use the field names, since they do not make much sense for loculus instances.
The "initialValue" prop is removed in favor of the "value" prop. This is now closer to the html input component. …
=> feat(components): improve design of location filter

components/src/preact/textInput/fetchAutocompleteList.ts
resolves https://github.com/GenSpectrum/dashboard-components/issues/514
=> feat(components): sort options of textput filter

components/src/preact/components/downshift-combobox.tsx, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/locationFilter/location-filter.tsx, components/src/preact/textInput/text-input.stories.tsx, components/src/preact/textInput/text-input.tsx, components/src/web-components/input/gs-text-input.stories.ts, components/src/web-components/input/gs-text-input.tsx
Resolves: #660
BREAKING CHANGE: Rename initialValue to value for text input
Extracts the common method to reduce code duplication and pave the road for #654
Also renames the initial value to value to be in line with the generic input component.
=> refactor: extract downshift combobox from location filter and text input

components/src/utils/mutations.ts
=> feat(components): allow mutations to end in *

components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.stories.ts, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
=> feat(components): add option to add info text to info bar for WISE graph

components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.stories.tsx, components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.stories.ts, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
=> docs(components): gs-wastewater-mutations-over-time: remove misplaced link in attribute docs

components/src/preact/components/tabs.tsx
=> feat(components): make component tabs layout better suited for multiline layout

components/src/web-components/gs-app.stories.ts, components/src/web-components/gs-app.ts, components/src/web-components/index.ts, components/src/web-components/input/gs-date-range-selector.stories.ts, components/src/web-components/input/gs-lineage-filter.stories.ts, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-text-input.stories.ts, components/src/web-components/visualization/gs-aggregate.stories.ts, components/src/web-components/visualization/gs-mutation-comparison.stories.ts, components/src/web-components/visualization/gs-mutations-over-time.stories.ts, components/src/web-components/visualization/gs-mutations.stories.ts, components/src/web-components/visualization/gs-number-sequences-over-time.stories.ts, components/src/web-components/visualization/gs-prevalence-over-time.stories.ts, components/src/web-components/visualization/gs-relative-growth-advantage.stories.ts, components/src/web-components/visualization/gs-sequences-by-location.stories.ts, components/src/web-components/visualization/gs-statistics.stories.ts, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.stories.ts
* The file name should match the custom HTLM tag name
* The component class is called <component without gs->Component
=> refactor(components): rename app file to match our usual convention

components/src/preact/dateRangeSelector/date-range-selector.stories.tsx
=> test(components): make sure that we actually await the assertions

components/src/preact/dateRangeSelector/date-range-selector.stories.tsx
so that it's executed again, even if the assertion afterwards fails. Maybe this makes the test less flaky.
=> test(components): put action in wait for

components/src/preact/mutationFilter/mutation-filter-info.tsx
=> fix(components): gs-mutation-filter: fix info wrongly showing "no nucleotide sequences" when there is only one

components/src/web-components/visualization/gs-aggregate.tsx
=> docs(components): gs-aggregate: make views type explicit to properly display it in storybook

components/package.json
https://docs.npmjs.com/cli/v11/commands/npm-pkg
npm did that during `release` anyway.
=> chore(components): run `npm pkg fix`

components/.prettierignore
It speeds up prettier and loading it on the stories.
=> chore(components): don't format the worldAtlas.json test data

components/src/preact/mutationsOverTime/mutations-over-time.stories.tsx, components/src/preact/mutationsOverTime/mutations-over-time.tsx, components/src/web-components/visualization/gs-mutations-over-time.stories.ts, components/src/web-components/visualization/gs-mutations-over-time.tsx
=> feat(components): gs-mutations-over-time: add `initialMeanProportionInterval` attribute

components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
=> fix(components): gs-wastewater-mutations-over-times: update when props change

components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx, components/src/preact/mutationsOverTime/mutations-over-time.tsx
resolves #744
I also felt that we should explain the numbers a bit, that's why I added a paragraph to the info box.
=> feat(components): gs-mutations-over-time: add the count of samples with coverage to grid cell tooltip

components/src/utilEntrypoint.ts
=> feat(components): export mutation annotations types

components/package-lock.json, components/package.json, components/src/preact/components/annotated-mutation.stories.tsx, components/src/preact/components/annotated-mutation.tsx, components/src/web-components/visualization/gs-mutations-over-time.stories.ts, components/src/web-components/visualization/gs-mutations.stories.ts
=> feat(components): allow HTML in mutation annotation description

components/src/web-components/MutationAnnotations.mdx, components/src/web-components/ResizeContainer.mdx, components/src/web-components/errorHandling.mdx, components/src/web-components/gs-app.ts, components/src/web-components/input/gs-date-range-filter.tsx, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-filter.tsx, components/src/web-components/visualization/gs-aggregate.tsx, components/src/web-components/visualization/gs-mutation-comparison.tsx, components/src/web-components/visualization/gs-mutations-over-time.tsx, components/src/web-components/visualization/gs-mutations.tsx, components/src/web-components/visualization/gs-number-sequences-over-time.tsx, components/src/web-components/visualization/gs-prevalence-over-time.tsx, components/src/web-components/visualization/gs-relative-growth-advantage.tsx, components/src/web-components/visualization/gs-sequences-by-location.tsx, components/src/web-components/visualization/gs-statistics.tsx, components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
=> docs(components): add mutations annotation docs

components/src/preact/mutationFilter/mutation-filter.tsx
=> fix(components): gs-mutation-filter: indicate that one can click the x button that deletes selected mutations

components/src/preact/mutationsOverTime/mutations-over-time-grid-tooltip.stories.tsx, components/src/preact/mutationsOverTime/mutations-over-time-grid-tooltip.tsx, components/src/preact/mutationsOverTime/mutations-over-time-grid.tsx
=> refactor(components): extract mutations-over-time-grid-tooltip and add story

components/package.json
=> chore(components): allow typescript minor version updates

components/.storybook-preact/preview.ts, components/.storybook/preview.tsx, components/src/componentsEntrypoint.ts, components/src/preact/components/error-display.stories.tsx, components/src/preact/components/error-display.tsx, components/src/preact/dateRangeFilter/date-range-filter.stories.tsx, components/src/preact/dateRangeFilter/date-range-filter.tsx, components/src/preact/dateRangeFilter/dateRangeOption.ts, components/src/preact/lineageFilter/LineageFilterChangedEvent.ts, components/src/preact/lineageFilter/lineage-filter.stories.tsx, components/src/preact/locationFilter/LocationChangedEvent.ts, components/src/preact/locationFilter/location-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.stories.tsx, components/src/preact/mutationFilter/mutation-filter.tsx, components/src/preact/textFilter/TextFilterChangedEvent.ts, components/src/preact/textFilter/text-filter.stories.tsx, components/src/utilEntrypoint.ts, components/src/utils/gsEventNames.ts, components/src/web-components/input/gs-date-range-filter.stories.ts, components/src/web-components/input/gs-date-range-filter.tsx, components/src/web-components/input/gs-lineage-filter.stories.ts, components/src/web-components/input/gs-lineage-filter.tsx, components/src/web-components/input/gs-location-filter.stories.ts, components/src/web-components/input/gs-location-filter.tsx, components/src/web-components/input/gs-mutation-filter.stories.ts, components/src/web-components/input/gs-mutation-filter.tsx, components/src/web-components/input/gs-text-filter.stories.ts, components/src/web-components/input/gs-text-filter.tsx, examples/React/src/App.tsx
=> feat(components): export event names in a constant

components/src/preact/components/min-max-range-slider.tsx, components/src/preact/dateRangeFilter/date-range-filter.stories.tsx, components/src/preact/numberRangeFilter/NumberRangeFilterChangedEvent.ts, components/src/preact/numberRangeFilter/number-range-filter.stories.tsx, components/src/preact/numberRangeFilter/number-range-filter.tsx, components/src/preact/numberRangeFilter/useSelectedRangeReducer.ts, components/src/utils/gsEventNames.ts, components/src/web-components/input/gs-number-range-filter.spec.ts, components/src/web-components/input/gs-number-range-filter.stories.ts, components/src/web-components/input/gs-number-range-filter.tsx, components/src/web-components/input/gs-text-filter.stories.ts, components/src/web-components/input/index.ts
=> 761 number input draft a suggestion

components/src/preact/genomeViewer/loadGff3.spec.ts, components/src/preact/genomeViewer/loadGff3.ts
=> feat(components): remove quotes from CDS name

.github/workflows/storybook.yml, components/.storybook/main.ts
It's unnecessary complexity that brings to real benefit
=> chore(components): remove integration of preact storybook into web component storybook

components/src/web-components/input/gs-number-range-filter.tsx
=> fix(components): fix type of event for gs-number-range-filter in docs

components/src/preact/numberRangeFilter/NumberRangeFilterChangedEvent.ts, components/src/utilEntrypoint.ts
=> feat(components): export number filter events

components/src/web-components/tutorials/CreateYourFirstOwnDashboard.mdx, components/src/web-components/tutorials/UseTheComponentsWithPlainJavaScript.mdx, components/src/web-components/tutorials/UseTheComponentsWithReact.mdx, examples/React/src/App.tsx
resolves #
I have started a tutorial for usage of the components in a plain js environment. It would be nice to get some feedback, if this is something you envisioned in #857 . If this is the case, I will also add a tutorial for react. 
=> docs(components): add tutorials

components/src/query/queryMutationsOverTime.ts
Small improvement to reduce API calls. If the user provides a start and end date already, we do not need to check the database for available dates. only when start, end or both are missing, we check.
n/a
=> feat(components): when user provides start and end date, do not query the database for available dates

components/README.md
=> docs(components): explain how building the published library works
